"""Lint the YAML frontmatter of the planning artifacts under ``docs/prd``.

The ``create-*`` / ``*-prd-to-issues`` skills always emit conforming frontmatter,
but a *legacy* or hand-written PRD may be missing the block entirely, carry the
wrong ``kind``, or omit required fields. This module scans the tree by **file
location** (not by parsing first, so a file with no fence is still reportable)
and returns a clear, concise list of what each artifact is missing — the input
the ``adopt-prd`` skill uses to fix up a whole directory at once.

Only the frontmatter-bearing artifacts are linted: ``docs/prd/epics/*/epic.md``
and ``docs/prd/*/prd.md``. Slice docs under ``slices/`` are machine-generated by
the ``*-prd-to-issues`` step and tracked by presence, not linted here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .frontmatter import FrontmatterError, parse
from .model import prd_root

# Allowed value domains, keyed by the artifact's expected kind.
_EPIC_STATUS = ("draft", "prds-planned", "in-progress", "done")
_PRD_STATUS = ("draft", "issues-created", "in-progress", "done")
_PRD_KINDS = ("feature", "capability")


@dataclass
class Report:
    """The lint result for one artifact file."""

    path: Path
    family: str                 # "epic" or "prd" — inferred from the file's location
    violations: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.violations


def _check_str(data: dict, key: str, out: list[str]) -> None:
    if key not in data:
        out.append(f"missing required field '{key}'")
    elif not isinstance(data[key], str) or not data[key].strip():
        out.append(f"field '{key}' is empty — expected a non-empty string")


def _check_choice(data: dict, key: str, choices: tuple[str, ...], out: list[str]) -> None:
    allowed = ", ".join(choices)
    if key not in data:
        out.append(f"missing required field '{key}' (expected one of: {allowed})")
    elif data[key] not in choices:
        out.append(f"field '{key}' is {data[key]!r} — must be one of: {allowed}")


def validate_data(data: dict, family: str, *, dir_name: str | None = None) -> list[str]:
    """Return the frontmatter violations of *data* for an artifact of *family*.

    *family* is ``"epic"`` or ``"prd"`` (the location-derived expectation). An
    empty list means the frontmatter conforms.
    """
    out: list[str] = []
    if family == "epic":
        _check_choice(data, "kind", ("epic",), out)
        _check_choice(data, "status", _EPIC_STATUS, out)
    else:  # prd
        _check_choice(data, "kind", _PRD_KINDS, out)
        _check_choice(data, "status", _PRD_STATUS, out)
    _check_str(data, "title", out)
    _check_str(data, "slug", out)
    if dir_name and isinstance(data.get("slug"), str) and data["slug"].strip():
        if data["slug"] != dir_name:
            out.append(f"slug {data['slug']!r} does not match directory name {dir_name!r}")
    return out


def validate_file(path: Path, family: str) -> Report:
    """Parse and lint a single artifact file, capturing a missing/broken fence."""
    try:
        doc = parse(path)
    except FrontmatterError as e:
        # Strip the redundant "<path>: " prefix the parser prepends.
        msg = str(e).split(": ", 1)[-1]
        return Report(path=path, family=family, violations=[f"no/invalid frontmatter: {msg}"])
    return Report(path=path, family=family, violations=validate_data(doc.data, family, dir_name=path.parent.name))


def candidate_files(root: Path) -> list[tuple[Path, str]]:
    """Every frontmatter-bearing artifact path under docs/prd, with its family.

    Enumerated by glob (not by ``discover_*``, which would raise on the first
    file lacking a fence), so unstructured files are still surfaced.
    """
    base = prd_root(root)
    out: list[tuple[Path, str]] = []
    epics = base / "epics"
    if epics.is_dir():
        for f in sorted(epics.glob("*/epic.md")):
            out.append((f, "epic"))
    if base.is_dir():
        for f in sorted(base.glob("*/prd.md")):
            if f.parent.parent.name == "epics":  # belt-and-braces
                continue
            out.append((f, "prd"))
    return out


def scan(root: Path) -> list[Report]:
    """Lint every artifact under docs/prd; returns one Report per file."""
    return [validate_file(path, family) for path, family in candidate_files(root)]
